# Generated by Django 2.2.27 on 2022-03-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flinderserver', '0002_auto_20220322_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='dateOfBirth',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='mixedYearOfBirth',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contactDetails',
            field=models.CharField(default=4532545363, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mixedAge',
            field=models.BooleanField(choices=[(True, 'Mixed'), (False, 'Same')], default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mixedGender',
            field=models.BooleanField(choices=[(True, 'Mixed'), (False, 'Same')], default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mixedYearOfStudy',
            field=models.BooleanField(choices=[(True, 'Mixed'), (False, 'Same')], default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='yearOfBirth',
            field=models.IntegerField(default=1999),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='addressLine1',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='addressLine2',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='flatBedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='freeBedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='postCode',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.DeleteModel(
            name='Preferences',
        ),
    ]
