# Generated by Django 2.2.26 on 2022-03-25 03:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flinderserver', '0002_auto_20220322_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='dateOfBirth',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='mixedYearOfBirth',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contactDetails',
            field=models.CharField(default='none', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mixedAge',
            field=models.BooleanField(choices=[(True, 'Mixed'), (False, 'Same')], default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mixedGender',
            field=models.BooleanField(choices=[(True, 'Mixed'), (False, 'Same')], default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mixedYearOfStudy',
            field=models.BooleanField(choices=[(True, 'Mixed'), (False, 'Same')], default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='yearOfBirth',
            field=models.IntegerField(default=2002),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='addressLine1',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='addressLine2',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='flatBedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='freeBedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='postCode',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['username'], name='flinderserv_usernam_fc2b61_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['uuid'], name='flinderserv_uuid_66ab2b_idx'),
        ),
        migrations.DeleteModel(
            name='Preferences',
        ),
    ]
