# Generated by Django 2.2.27 on 2022-03-25 19:53

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flinderserver', '0003_auto_20220325_0346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='interests',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interests',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('pets', 'pets'), ('food', 'food'), ('sports', 'sports'), ('music', 'music'), ('partying', 'partying'), ('drinking', 'drinking'), ('flatCleanliness', 'flatCleanliness'), ('strictQuietHours', 'strictQuietHours')], default='', max_length=73),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='InterestsAndPriorities',
        ),
    ]
