# Generated by Django 2.2.27 on 2022-03-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flinderserver', '0004_auto_20220325_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
